export const PRICING_ACTION_SET = 'PRICING_ACTION_SET';
export const PRICING_ACTION_FILTER = 'PRICING_ACTION_FILTER';
export const PRICING_ACTION_FETCHING = 'PRICING_ACTION_LOADING';
export const PRICING_ACTION_CALCULATING = 'PRICING_ACTION_CALCULATING';
